### ISSUE TITLE
Deprecation warning when converting Draw.io images to svgs

### ISSUE THREAD

**Issue by steinwelberg** [LukeCarrier/mkdocs-drawio-exporter#17]
I get the following deprecation warning when building a Mkdocs website that contains draw.io images.

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:58589) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
(node:58589) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.
```

For every Draw.io image the above message is printed.

I'm using a Mac that has Draw.io 13.0.3 installed using Homebrew Cask.

My drawio-exporter config:
```
    - drawio-exporter:
          cache_dir: 'rendered-diagrams'
          format: svg
          sources: '*.drawio'
```
