### ISSUE TITLE
Using an <object> tag in created svg

### ISSUE THREAD

**Issue by leros321** [LukeCarrier/mkdocs-drawio-exporter#20]
We are using your plugin within mkdocs pages with svg format. We found out, we cannot use interactivity within svg(hyperlinks) if `<img>` tag is used.

Is it possible instead of `<img>` tag to use `<object>` tag?

We tested it as following and hyperlinks from svg works only in object
`<object type="image/svg+xml" data="image.svg"></object>`

**Comment by LukeCarrier** [comment]
@leros321 are you able to take a look at the changes in #24 for me? It should be possible to achieve what you're looking for with a configuration like this now:

```yaml
plugins:
  - drawio-exporter:
    embed_format: '<object type="image/svg+xml" data="{img_src}"></object>'
```
