### ISSUE TITLE
Errors when using plugin in Github Actions

### ISSUE THREAD

**Issue by ab185508** [LukeCarrier/mkdocs-drawio-exporter#30]
I am trying to implement the plugin as part of a github action that builds a mkdocs site to github pages.

The steps in the action install all the components but for some reason when it gets to the step of actually deploying the site it errors out.

Error:
```
mkdir: cannot create directory ‘/run/user/1001’: Permission denied 
ERROR  -  Export failed with exit status 1; skipping copy
```

Action:
```
name: gh page ci 
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install \
              mkdocs-material \
              mkdocs-drawio-exporter \

      - run: sudo apt-get update
      - run: sudo snap install drawio
      - run: mkdocs gh-deploy --force
```

Any thoughts on how to fix this?
