### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by brunopenso** [LukeCarrier/mkdocs-drawio-exporter#32]
Hello everyone if you are here with some kind of difficult to use and make it work here is the github actions file working perfect well.

```
name: ci 
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: sudo apt-get install -y libasound2 xvfb
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-drawio-exporter
      - name: Install drawio
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v18.1.3/drawio-amd64-18.1.3.deb
          sudo dpkg -i drawio-amd64-18.1.3.deb
      - run: xvfb-run -a mkdocs gh-deploy --force
```

Thanks @LukeCarrier for yout extension/plugin
