### ISSUE TITLE
Issue with using inside docker container

### ISSUE THREAD

**Issue by BaluVyamajala** [LukeCarrier/mkdocs-drawio-exporter#67]
Trying to setup a development server for running mkdocs locally. so, users don't have to install draw io in their mac/windows systems. But several things I have tried and finally left at below configuration which goes into infinate loop trying to export images for draw.io?

Here is my Docker file:

```
from python:3.8

WORKDIR /app


ARG drawio_arch=amd64
ARG drawio_version=18.1.3
ARG drawio_deb="drawio-${drawio_arch}-${drawio_version}.deb"
ARG drawio_url="https://github.com/jgraph/drawio-desktop/releases/download/v${drawio_version}/${drawio_deb}"

RUN curl -L -o "$drawio_deb" "$drawio_url"
RUN apt-get update && \
    apt-get install -y libasound2 xvfb ./"$drawio_deb"

EXPOSE 8000

COPY requirements.txt .
RUN pip install -r requirements.txt 
COPY . /docs/
COPY ./mkdocs.yml . 

ENTRYPOINT ["xvfb-run", "mkdocs"]
CMD ["serve"]
```

docker-compose.yaml

```
services:
  web:
    build: .
    volumes:
      - ./docs:/app/docs
      - ./mkdocs.yml:/app/mkdocs.yml
    ports:
      - "8000:8000"
    privileged: true
    init: true
```

extensions:
```
markdown_extensions:
  - tables
  - attr_list
plugins:
  - drawio-exporter:
      cache_dir: 'assets/drawings/drawio-exporter'
      drawio_args:
        - --no-sandbox
```

<img width="1321" alt="image" src="https://github.com/LukeCarrier/mkdocs-drawio-exporter/assets/23091268/01ad6275-cb61-4b47-ab0a-7661bd328dd0">

Any help would be greatly appreciated.
