### ISSUE TITLE
Adding Plugin Breaks Navigation to Nested Files

### ISSUE THREAD

**Issue by Hamzah-Haider** [LukeCarrier/mkdocs-drawio-exporter#83]
Adding the plugin to mkdocs.yml breaks navigation to multi-nested file directories.

Current mkdocs.yml
```
site_name: Docs
theme:
  name: mkdocs
  color_mode: dark
  nav_style: dark

docs_dir: docs
plugins:
  - drawio-exporter
```

docs/file.md (works)
docs/folder/file.md (works)
docs/folder/folder/file.md (broken)

Removing the plugin declaration:
```
plugins:
  - drawio-exporter
```
from the mkdocs.yml, fixes the issue.

Attempt to navigate to docs/folder/folder/file.md from mkdocs client with plugin active:
Mkdocs Resolved URL: http://127.0.0.1:8000/test/test/#
![image](https://github.com/user-attachments/assets/a6166ce2-5160-4ae5-aaeb-97c6035ff827)
Behaviour: Does nothing on click, does not show any files in folder drop down

Attempt to navigate to docs/folder/folder/file.md from mkdocs client without plugin:
Mkdocs Resolved URL: http://127.0.0.1:8000/test/test/test/
![image](https://github.com/user-attachments/assets/4b8cdb75-1394-4e41-bd37-a6be7925e983)
Behaviour: Shows drop-down options on click, successfully resolves URL path and renders document
